# Form implementation generated from reading ui file 'proses.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sqlite3
import sys
import os

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(787, 527)
        self.tableView = QtWidgets.QTableView(parent=Form)
        self.tableView.setGeometry(QtCore.QRect(60, 80, 681, 261))
        self.tableView.setObjectName("tableView")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(460, 20, 181, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(660, 20, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(380, 20, 61, 31))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 360, 91, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 360, 91, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_4.setGeometry(QtCore.QRect(650, 360, 91, 31))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Cari"))
        self.label.setText(_translate("Form", "Searching"))
        self.pushButton_2.setText(_translate("Form", "Sebelumnya"))
        self.pushButton_3.setText(_translate("Form", "Selanjutnya"))
        self.pushButton_4.setText(_translate("Form", "Update All"))

    def refreshTableView(self):
        self.tableView.setModel(self.model)

    def populateTable(self):
        query = self.db.execute("SELECT * FROM proses")
        columnHeaders = [description[0] for description in query.description]
        self.model = QtGui.QStandardItemModel()
        self.model.setHorizontalHeaderLabels(columnHeaders)
        for row in query:
            items = [QtGui.QStandardItem(str(item)) for item in row]
            self.model.appendRow(items)
        self.tableView.setModel(self.model)
        return self.model

    def cariData(self):
        id = self.lineEdit.text()
        query = self.db.execute("SELECT * FROM proses WHERE id=?", (id,))
        columnHeaders = [description[0] for description in query.description]
        self.model = QtGui.QStandardItemModel()
        self.model.setHorizontalHeaderLabels(columnHeaders)
        for row in query:
            items = [QtGui.QStandardItem(str(item)) for item in row]
            self.model.appendRow(items)
        self.tableView.setModel(self.model)

    def tambahData(self):
        id = self.editId.text()
        iduser = self.editIduser.text()
        idtas = self.editIdtas.text()
        waktu = self.editWaktu.text()
        kategori = self.editKategori.text()
        berat = self.editBerat.text()
        total = self.editTotal.text()
        self.db.execute("INSERT INTO proses (id, iduser, idtas, waktu, kategori, berat, total) VALUES (?, ?, ?, ?, ?, ?, ?)", (id, iduser, idtas, Waktu, kategori, berat, total))
        self.db.commit()
        self.refreshTableView()
        self.editId.setText("")
        self.editIduser.setText("")
        self.editIdtas.setText("")
        self.editWaktu.setText("")
        self.editKategori.setText("")
        self.editBerat.setText("")
        self.editTotal.setText("")

    def ubahData(self):
        id = self.editId.text()
        iduser = self.editIduser.text()
        idtas = self.editIdtas.text()
        waktu = self.editWaktu.text()
        kategori = self.editKategori.text()
        berat = self.editBerat.text()
        total = self.editTotal.text()
        self.db.execute("UPDATE proses SET iduser=?, idtas=?, Waktu=?, kategori=?, berat=?, total=? WHERE id=?", (iduser, idtas, Waktu, kategori, berat, total, id))
        self.db.commit()
        self.refreshTableView()
        self.editId.setText("")
        self.editIduser.setText("")
        self.editIdtas.setText("")
        self.editWaktu.setText("")
        self.editKategori.setText("")
        self.editBerat.setText("")
        self.editTotal.setText("")

    def hapusData(self):
        id = self.editId.text()
        self.db.execute("DELETE FROM proses WHERE id=?", (id,))
        self.db.commit()
        self.refreshTableView()
        self.editId.setText("")
        self.editIduser.setText("")
        self.editIdtas.setText("")
        self.editWaktu.setText("")
        self.editKategori.setText("")
        self.editBerat.setText("")
        self.editTotal.setText("")

    def updateAll(self, iduser, idtas, waktu, kategori, berat, total, id):
        self.db.execute("UPDATE proses SET iduser=?, idtas=?, Waktu=?, kategori=?, berat=?, total=? WHERE id=?", (iduser, idtas, waktu, kategori, berat, total, id))
        self.db.commit()
        self.refreshTableView()
        # Bersihkan input setelah pembaruan
        
    def getIdUser(self):
        return self.editIduser.text()

    def getIdTas(self):
        return self.editIdtas.text()

    def getWaktu(self):
        return self.editWaktu.text()

    def getKategori(self):
        return self.editKategori.text()

    def getBerat(self):
        return self.editBerat.text()

    def getTotal(self):
        return self.editTotal.text()

    def getId(self):
        return self.editId.text()

    

class ProsesApp(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()

        self.ui = Ui_Form()
        self.ui.setupUi(self)

        # Koneksi ke database
        self.conn = sqlite3.connect('laundry.db')  # Ganti dengan nama database Anda
        self.cursor = self.conn.cursor()

        self.ui.db = self.conn  # Menyimpan koneksi database ke atribut db pada objek Ui_Form
        self.ui.populateTable()  # Memanggil fungsi populateTable tanpa parameter
        self.ui.pushButton_4.clicked.connect(self.callUpdateAll)

    def callUpdateAll(self):
        # Dapatkan data dari GUI Anda
        iduser = self.ui.getIdUser()  
        idtas = self.ui.getIdTas()    
        waktu = self.ui.getWaktu()    
        kategori = self.ui.getKategori()  
        berat = self.ui.getBerat()    
        total = self.ui.getTotal()    
        id = self.ui.getId()          

        # Panggil fungsi updateAll() pada objek ui
        self.ui.updateAll(iduser, idtas, waktu, kategori, berat, total, id)

def main():
    app = QtWidgets.QApplication([])
    window = ProsesApp()
    window.show()
    app.exec()

if __name__ == "__main__":
    main()